name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: issues_tracker
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: cd backend && pip install -r requirements.txt
      - run: cd backend && pytest
      - run: cd frontend && npm install
      - run: cd frontend && npm run test